version: '3'

services:
  businessinfo:
    image: davidseid/business_info_deploy:deploy
    depends_on:
      - 'mongo'
      - 'redis'
    environment:
      - REDIS_HOST=redis
      - DATABASE_HOST=mongo
      - HOST=localhost
    ports:
      - '3003:3003'
  proxy:
    image: davidseid/dsproxy_deploy:deploy
    depends_on:
      - 'mongo'
      - 'redis'
      - 'businessinfo'
    environment:
      - BUSINESS_INFO_ADDRESS=businessinfo
      - HOST=localhost
    ports:
      - '3000:3000'
  mongo:
    image: mongo:latest
    volumes:
      - business_info_db:/var/lib/docker
  redis:
    image: redis:3.2-alpine

volumes:
  business_info_db: